services:
  - type: web
    name: nextwork-backend-api
    runtime: node
    buildCommand: NPM_CONFIG_PRODUCTION=false npm ci --include=dev && npm run build --workspace backend-api
    startCommand: npm run start --workspace backend-api
    healthCheckPath: /api/v1/health/live
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20